import google.generativeai as genai
import config

def analyze_stock(stock_data):
    """
    Analyzes stock data using Gemini.
    
    Args:
        stock_data (dict): Dictionary containing stock history and news.
        
    Returns:
        str: The analysis report generated by the LLM.
    """
    if not config.GEMINI_API_KEY:
        return "Error: Gemini API Key is missing."
        
    genai.configure(api_key=config.GEMINI_API_KEY)
    model = genai.GenerativeModel('gemini-pro')
    
    prompt = f"""
    You are a financial analyst. Analyze the following stock data and news to provide a summary and investment outlook.
    
    Data:
    {stock_data}
    
    Please provide a concise report for each stock, highlighting key trends and any red flags based on the news.
    """
    
    try:
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"Error generating analysis: {e}"

if __name__ == "__main__":
    # Test run (mock data)
    mock_data = {
        "AAPL": {"current_price": 150, "news": ["Apple releases new iPhone", "Stocks up"]},
        "GOOGL": {"current_price": 2800, "news": ["Google AI updates"]}
    }
    print(analyze_stock(mock_data))
